name: Hello World Workflow

on:
  push:
    branches:
      - master
    paths: 
      - '.github/workflows/helloworldworkflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world"
      - name: say bye
        run: echo "good "
