name: Hello World Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Say Hello
        run: echo "Hello, world"
      - name: say bye
        run: echo "catch u later"
